insert INTO Genre(genre) VALUES ('rock');
insert INTO Genre(genre) VALUES ('hard rock');
insert INTO Genre(genre) VALUES ('new wave');
INSERT INTO Performers(performer) VALUES('Accept');
INSERT INTO Performers(performer) VALUES('AC/DC');
INSERT INTO Performers(performer) VALUES('Police');
INSERT INTO Performers(performer) VALUES('Queen');
select * from performers ;
INSERT into genreperformer VALUES  (1, 4);
INSERT into genreperformer VALUES  (2, 1);
INSERT into genreperformer VALUES  (2, 2);
INSERT into genreperformer VALUES  (3, 3);
INSERT into albums values (default, 'Balls To The Wall', 1983);
INSERT into albums values (default, 'Back In Black', 1980);
INSERT into albums values (default, 'Synchronicity', 1983);
INSERT into albums values (default, 'Innuendo', 1991);
INSERT into albums values (default, 'Power Up', 2020);

INSERT into perfomeralbum values(1, 1);
INSERT into perfomeralbum values(2, 2);
INSERT into perfomeralbum values(3, 3);
INSERT into perfomeralbum values(4, 4);
INSERT into perfomeralbum values(2, 5);
INSERT into track values (default, 1, 'Love Child',214);
INSERT into track values (default, 1, 'Winter Dreams',292);
INSERT into track values (default, 2, 'Shoot To Thrill',314);
INSERT into track values (default, 2, 'Shake A Leg',243);
INSERT into track values (default, 3, 'King Of Pain',299);
INSERT into track values (default, 3, 'Tea In The Sahara',259);
INSERT into track values (default, 4, 'Innuendo',389);
INSERT into track values (default, 4, 'Delilah',212);
INSERT into track values (default, 5, 'Rejection',246);
INSERT into track values (default, 5, 'My Shot',185);
INSERT into compilations values (default, 'Cat Love', 1992);
INSERT into compilations values (default, 'Winter Desert', 1984);
INSERT into compilations values (default, 'Eternity', 1993);
INSERT into compilations values (default, 'Energy', 1983);
INSERT into compilations values (default, 'Total Rejection', 2020);
INSERT into trackscompilation values(1, 1);
INSERT into trackscompilation values(8, 1);
INSERT into trackscompilation values(2, 2);
INSERT into trackscompilation values(6, 2);
INSERT into trackscompilation values(2, 3);
INSERT into trackscompilation values(7, 3);
INSERT into trackscompilation values(1, 4);
INSERT into trackscompilation values(3, 4);
INSERT into trackscompilation values(3, 5);
INSERT into trackscompilation values(9, 5);